### PR TITLE
add hbase parent znode env

### PR DESCRIPTION
**Pull request by swift1911**

### CODE REVIEW

**Comment by RoySRose** [comment]
Hello, @swift1911 

I think a few things need to be modified.

1. ./.env file 
2. which one is correct? isn't 2nd one correct? just like the others?
```text
sed -i "/hbase.zookeeper.znode.parent=/ s/=.*/=\\${HBASE_ZNODE_PARENT}/" /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hbase.properties
```

```text
sed -i "/hbase.zookeeper.znode.parent=/ s/=.*/=${HBASE_ZNODE_PARENT}/" /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hbase.properties
```

**Comment by swift1911** [comment]
@RoySRose 1st is correct , if you set HBASE_ZNODE_PARENT=/hbase-unsecure is will cause syntax error

sed -i '/hbase.zookeeper.znode.parent=/ s/=.*/=/hbase-unsecure/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hbase.properties

sed: -e expression #1, char 41: unknown option to `s'

**Comment by RoySRose** [comment]
@swift1911 
I'll check your updates.
While I'm on it.
1.  Can you combine your commits to one?
2. Also, Can you rebase instead of merge? 
all pinpoint repositories are following rebase policy
here are the link on rebase
https://www.atlassian.com/git/tutorials/merging-vs-rebasing
https://medium.com/datadriveninvestor/git-rebase-vs-merge-cc5199edd77c

**Comment by swift1911** [comment]
@RoySRose done.

**Comment by RoySRose** [comment]
@swift1911 
Great~!
I'll merge with the v1.9.0 release

**Pull request closed without merging**
