### PR TITLE
Send alarms by email

### PR DESCRIPTION
**Pull request by marcosamm**
Addition of mysql container with pinpoint database to allow the 
registration of users, groups and alarms.

Including lib, implementation of AlarmMessageSender and settings 
in the pinpoint-web container to allow sending alert emails.

### CODE REVIEW

**Comment by RoySRose** [comment]
Hello, @marcosamm 

First of all, Thank you for your interest in Pinpoint community.

I'm going through your PR and it's Almost Perfect~! Just one thing.

Can you wrap the parameters below and put it in *`.env`* file?
There are two *`.env`* files. First you can put all the parameters in 
*`.env`* under `pinpoint-web/.env` and just copy it and replace only the web part in `./.env`

```text
      - JDBC_DRIVER=com.mysql.jdbc.Driver
      - JDBC_URL=jdbc:mysql://pinpoint-mysql:3306/pinpoint?characterEncoding=UTF-8
      - JDBC_USERNAME=admin
      - JDBC_PASSWORD=admin
      - MAIL_HOST=stmp.test.com
      - MAIL_PORT=123
      - MAIL_USERNAME=user
      - MAIL_PASSWORD=pass
#      - MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL=smtp
      - MAIL_PROPERTIES_MAIL_SMTP_AUTH='true'
      - MAIL_PROPERTIES_MAIL_SMTP_PORT=587
#      - MAIL_PROPERTIES_MAIL_SMTP_FROM=test@example.com
      - MAIL_PROPERTIES_MAIL_STARTTLS_ENABLE='true'
#      - MAIL_PROPERTIES_MAIL_STARTTLS_REQUIRED='true'
#      - MAIL_PROPERTIES_MAIL_DEBUG='true'
```

Within this way everyone can just download the image from [docker-hub](https://hub.docker.com/) and use it with the parameters they want without recreating the container image.

I think you will understand right away just by looking at the `.env` file
Just for example.

docker-compose
```text
      - JDBC_USERNAME=${JDBC_USERNAME}
```
.env file
```text
JDBC_USERNAME=admin
```


If you have any question. feel free to ask~

Have a nice day :)

**Comment by RoySRose** [comment]
@marcosamm 
And It would be GREAT~!
If you can update the readme.md about the alarm.

image

**Comment by marcosamm** [comment]
Hello, @RoySRose. 

You were faster than me ... I did not have time to post my comments here (after my commit) and thanks. 

I have a suggestion related to this pull request: include the implementation of AlarmSender (contained in the mail.zip file) and its dependencies in the pinpoint project (pinpoint-web). This will allow you to remove the mail.zip file from pinpoint-docker and it would be easier to evolve the alarm send implementation. I know that the existing implementation in the mail.zip file is very simple, but it is enough to make sending email alerts functional. What do you think?

**Comment by minwoo-jung** [comment]
Hi @marcosamm, @RoySRose
That's a good idea.^^

I was going to provide the mail sender for alarm.
As you say, That means that mail.zip file will be deleted.

But AlarmMessageSenderImple class without modification cann't be push pinpoint-web.
It is need to improved class extendability. So I will commit to change alarmsender logic. This logic can that your mail sender class be autowired to alarmsender class.

I can do everything, but I want to provide you with having an opportunity to commit.
First of all, I will improve alarm logic and I contact to you. 
And then you will need to PR for mail sender class and change docker code(delete mail.zip, edit script)
Can you do that?^^

**Comment by marcosamm** [comment]
Hi @minwoo-jung, @RoySRose 

Yes, I can do the PR after your improvements.

**Comment by minwoo-jung** [comment]
Hi @marcosamm
I completed development https://github.com/naver/pinpoint/issues/5052.
But I will merge this function after 1.8.1 release. And I will update alarm guide doc.

I also developd [implemented class for mailSender](https://github.com/minwoo-jung/pinpoint/commit/1d6299e7518a9ead1517e1531277d2823aebd2e1#diff-1cd4e7adbb77468717eaf60c69ac0fe6). Becuase I need to consider a mail contents and I have made class naturally.

could you update docker logic after 1,8.1 release and merging?

**Comment by marcosamm** [comment]
Hi @minwoo-jung 
Sorry for the delay.
I finished the changes [.](https://github.com/marcosamm/pinpoint-docker/commit/2dc86d073e4cddd7a708d5581c40130d5f067647). But I don't PR.
Basically I needed to modify the logic to only change the batch.properties file (using start-web.sh), adding the variables related to the email (pinpoint.url, alarm.mail.server.url, alarm.mail.server.port, alarm.mail.server.userName, alarm.mail.server.password, alarm.mail.sender.address).

**Comment by minwoo-jung** [comment]
@marcosamm
Thank you for your contribution. Maybe I will do PR next week because we

**Comment by minwoo-jung** [comment]
Hi @marcosamm
I'm sorry about answering late because there was internal release issue.
I completed PR.^^ I updated [guide](https://github.com/naver/pinpoint/commit/ad4b7942f684d9d72a8e2dd040615e4adbe62f13).

Could you update docker logic? If you could do that, we’d appreciate it.^^

**Comment by marcosamm** [comment]
Hello @ minwoo-jung

I updated the docker logic, but the tests can only be realized in fact after the release of version 1.9.0. Meanwhile the PR (#15) should not be merged.

**Comment by minwoo-jung** [comment]
Hi @marcosamm 
Thank you for your contribution.^^ I think the response is really fast.

@RoySRose 
I would like to ask a review,

**Pull request merged**
